(function(){
  const states=new WeakMap();
  function build(host){host.replaceChildren();const canvas=document.createElement('canvas');canvas.setAttribute('aria-label','Selected two-dimensional density with attached one-dimensional projections');canvas.style.cssText='display:block;width:100%;height:100%;background:#04101a';host.append(canvas);const state={host,canvas,view:''};states.set(host,state);return state}
  const rgba=(c,a)=>`rgba(${Math.round(c[0]*255)},${Math.round(c[1]*255)},${Math.round(c[2]*255)},${a})`;
  function smooth1d(a,r=7,passes=3){let src=Float64Array.from(a),dst=new Float64Array(a.length);for(let p=0;p<passes;p++){let sum=0;for(let i=-r;i<=r;i++)sum+=src[Math.max(0,Math.min(src.length-1,i))];for(let i=0;i<src.length;i++){dst[i]=sum/(2*r+1);sum-=src[Math.max(0,i-r)];sum+=src[Math.min(src.length-1,i+r+1)]}[src,dst]=[dst,src]}return src}
  function histogram(samples,dim,lo,hi,n=260){const raw=new Float64Array(n);for(const s of samples){const u=(s[dim]-lo)/(hi-lo)*(n-1),i=Math.floor(u),f=u-i;if(i>=0&&i<n)raw[i]+=1-f;if(i+1>=0&&i+1<n)raw[i+1]+=f}const a=dim==='z'?smooth1d(raw,2,1):smooth1d(raw);let max=0;for(const v of a)max=Math.max(max,v);return{a,max:max||1}}
  function componentHistograms(samples,dim,range,palette){const key=dim==='y'?'yBranch':'zBranch';return palette.map((_,q)=>histogram(samples.filter(s=>s[key]===q),dim,...range))}
  function drawHorizontal(c,hist,left,baseline,width,height,color,ratio,dash=[]){c.strokeStyle=color;c.lineWidth=1.7*ratio;c.setLineDash(dash);c.beginPath();for(let i=0;i<hist.a.length;i++){const x=left+i/(hist.a.length-1)*width,y=baseline-hist.a[i]/hist.max*height;i?c.lineTo(x,y):c.moveTo(x,y)}c.stroke()}
  function drawVertical(c,hist,edge,top,height,width,color,ratio,dash=[]){c.strokeStyle=color;c.lineWidth=1.7*ratio;c.setLineDash(dash);c.beginPath();for(let i=0;i<hist.a.length;i++){const y=top+height-i/(hist.a.length-1)*height,x=edge+hist.a[i]/hist.max*width;i?c.lineTo(x,y):c.moveTo(x,y)}c.stroke()}
  function densityLayer(c,samples,dx,dy,rx,ry,left,top,mw,mh,opacity){if(!samples.length)return;const gw=140,gh=96,n=gw*gh,count=new Float64Array(n),red=new Float64Array(n),green=new Float64Array(n),blue=new Float64Array(n),hasStrongAxis=dx==='z'||dy==='z',blurPasses=hasStrongAxis?1:3,displayCutoff=hasStrongAxis?.025:0;for(const s of samples){const gx=(s[dx]-rx[0])/(rx[1]-rx[0])*(gw-1),gy=(ry[1]-s[dy])/(ry[1]-ry[0])*(gh-1),ix=Math.floor(gx),iy=Math.floor(gy),fx=gx-ix,fy=gy-iy;if(ix<0||ix>=gw||iy<0||iy>=gh)continue;for(let oy=0;oy<=1;oy++)for(let ox=0;ox<=1;ox++){const xx=ix+ox,yy=iy+oy;if(xx<0||xx>=gw||yy<0||yy>=gh)continue;const weight=(ox?fx:1-fx)*(oy?fy:1-fy),k=yy*gw+xx;count[k]+=weight;red[k]+=s.color[0]*weight;green[k]+=s.color[1]*weight;blue[k]+=s.color[2]*weight}}function blur(a){let src=a,dst=new Float64Array(n);for(let pass=0;pass<blurPasses;pass++){for(let y=0;y<gh;y++)for(let x=0;x<gw;x++){let sum=0,weight=0;for(let oy=-1;oy<=1;oy++)for(let ox=-1;ox<=1;ox++){const xx=Math.max(0,Math.min(gw-1,x+ox)),yy=Math.max(0,Math.min(gh-1,y+oy)),wgt=(2-Math.abs(ox))*(2-Math.abs(oy));sum+=src[yy*gw+xx]*wgt;weight+=wgt}dst[y*gw+x]=sum/weight}[src,dst]=[dst,src]}return src}const dc=blur(count),dr=blur(red),dg=blur(green),db=blur(blue);let peak=0;for(const v of dc)peak=Math.max(peak,v);if(!peak)return;const off=document.createElement('canvas');off.width=gw;off.height=gh;const oc=off.getContext('2d'),img=oc.createImageData(gw,gh);for(let i=0;i<n;i++){const q=dc[i]/peak,a=q<displayCutoff?0:Math.pow(q,.48)*opacity,j=i*4,den=Math.max(dc[i],1e-8);img.data[j]=Math.min(255,255*dr[i]/den);img.data[j+1]=Math.min(255,255*dg[i]/den);img.data[j+2]=Math.min(255,255*db[i]/den);img.data[j+3]=Math.min(255,255*a)}oc.putImageData(img,0,0);c.save();c.globalCompositeOperation='lighter';c.imageSmoothingEnabled=true;c.imageSmoothingQuality='high';c.drawImage(off,left,top,mw,mh);c.restore()}
  function draw(host,view,d){let state=states.get(host);if(!state||state.canvas.parentNode!==host)state=build(host);state.view=view;const canvas=state.canvas,rect=canvas.getBoundingClientRect(),ratio=Math.min(devicePixelRatio||1,2),w=Math.max(2,Math.round(rect.width*ratio)),h=Math.max(2,Math.round(rect.height*ratio));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}const c=canvas.getContext('2d'),labelScale=d.labelScale||1.3,dims=view==='xy'?['x','y','z']:view==='xz'?['x','z','y']:['y','z','x'],[dx,dy,hidden]=dims,rx=d.ranges[dx],ry=d.ranges[dy],left=48*labelScale*ratio,top=32*labelScale*ratio,right=112*labelScale*ratio,bottom=88*labelScale*ratio,mw=w-left-right,mh=h-top-bottom,px=v=>left+(v-rx[0])/(rx[1]-rx[0])*mw,py=v=>top+mh-(v-ry[0])/(ry[1]-ry[0])*mh;
    c.fillStyle='#04101a';c.fillRect(0,0,w,h);c.fillStyle='#cce3ef';c.font=`bold ${13*labelScale*ratio}px Arial`;c.textAlign='left';c.fillText(`${dx.toUpperCase()}–${dy.toUpperCase()} density`,left,21*labelScale*ratio);c.fillStyle='#8faebe';c.font=`${10*labelScale*ratio}px Arial`;c.fillText(d.mode==='conditional'?`conditional slice at actual ${hidden.toUpperCase()}`:`projected density (integrated over ${hidden.toUpperCase()})`,left+145*labelScale*ratio,21*labelScale*ratio);
    const hiddenValue=d.particles[0]?.[hidden]??0,band=hidden==='x'?(d.ranges.x[1]-d.ranges.x[0])*.055:.22,conditional=d.samples.filter(s=>Math.abs(s[hidden]-hiddenValue)<band),projected=d.samples,main=d.mode==='conditional'?conditional:projected;
    densityLayer(c,main,dx,dy,rx,ry,left,top,mw,mh,.76);
    if(dx==='x'&&d.detectors?.length){c.save();c.lineWidth=1.6*ratio;c.font=`bold ${10*labelScale*ratio}px Arial`;c.textAlign='center';for(const detector of d.detectors){const x=px(detector.x);c.setLineDash([7*ratio,5*ratio]);c.strokeStyle=detector.color;c.beginPath();c.moveTo(x,top);c.lineTo(x,top+mh);c.stroke();c.setLineDash([]);const text=detector.label;c.fillStyle='#04101ae8';const tw=c.measureText(text).width+10*ratio;c.fillRect(x-tw/2,top+5*ratio,tw,16*labelScale*ratio);c.fillStyle=detector.color;c.fillText(text,x,top+17*labelScale*ratio)}c.restore()}
    c.save();c.setLineDash([5*ratio,5*ratio]);for(let q=0;q<d.results.length;q++){if(d.activeResult!=null&&q!==d.activeResult)continue;const v=d.results[q],col=rgba(d.palette[q],.72);if(dx!=='x'){const x=px(v);c.strokeStyle=col;c.beginPath();c.moveTo(x,top);c.lineTo(x,top+mh);c.stroke()}if(dy!=='x'){const y=py(v);c.strokeStyle=col;c.beginPath();c.moveTo(left,y);c.lineTo(left+mw,y);c.stroke()}}c.restore();
    c.strokeStyle='#7195aa';c.lineWidth=1.2*ratio;c.strokeRect(left,top,mw,mh);c.fillStyle='#c7dce8';c.font=`bold ${11*labelScale*ratio}px Arial`;c.textAlign='right';c.fillText(dx==='x'?'X':dx.toUpperCase()+'cal',left+mw,top+mh+18*labelScale*ratio);c.save();c.translate(left-14*labelScale*ratio,top);c.rotate(-Math.PI/2);c.textAlign='right';c.fillText(dy==='x'?'X':dy.toUpperCase()+'cal',0,0);c.restore();
    const actual=d.particles[0]??{x:0,y:0,z:0},sliceBand=dim=>dim==='x'?(d.ranges.x[1]-d.ranges.x[0])*.055:.22,
      xCurveSamples=d.mode==='conditional'?main.filter(s=>Math.abs(s[dy]-actual[dy])<sliceBand(dy)):main,
      yCurveSamples=d.mode==='conditional'?main.filter(s=>Math.abs(s[dx]-actual[dx])<sliceBand(dx)):main,
      sets=[[d.mode,xCurveSamples,yCurveSamples,d.mode==='conditional'?'#f2a7ff':'#edf8ff',false]];
    for(const [,xSamples,ySamples,color,dash] of sets){
      const hx=histogram(xSamples,dx,...rx),hy=histogram(ySamples,dy,...ry),lineDash=dash?[5*ratio,4*ratio]:[],componentsX=dx==='x'?[]:componentHistograms(xSamples,dx,rx,d.palette),componentsY=dy==='x'?[]:componentHistograms(ySamples,dy,ry,d.palette);
      for(let q=0;q<componentsX.length;q++){const component=componentsX[q];component.max=hx.max;if(component.a.some(v=>v>0))drawHorizontal(c,component,left,top+mh+bottom*.72,mw,bottom*.48,rgba(d.palette[q],.9),ratio,lineDash)}
      for(let q=0;q<componentsY.length;q++){const component=componentsY[q];component.max=hy.max;if(component.a.some(v=>v>0))drawVertical(c,component,left+mw,top,mh,right*.68,rgba(d.palette[q],.9),ratio,lineDash)}
      drawHorizontal(c,hx,left,top+mh+bottom*.72,mw,bottom*.48,color,ratio,lineDash);drawVertical(c,hy,left+mw,top,mh,right*.68,color,ratio,lineDash)
    }
    c.setLineDash([]);c.fillStyle='#a9c2d0';c.font=`${10*labelScale*ratio}px Arial`;c.textAlign='center';c.fillText(`${dx==='x'?'X':dx.toUpperCase()+'cal'} projection`,left+mw/2,h-8*labelScale*ratio);c.save();c.translate(w-9*labelScale*ratio,top+mh/2);c.rotate(-Math.PI/2);c.fillText(`${dy==='x'?'X':dy.toUpperCase()+'cal'} projection`,0,0);c.restore();
    for(const p of d.particles){const x=px(p[dx]),y=py(p[dy]);c.fillStyle='#ffe49b';c.strokeStyle='#4c3510';c.lineWidth=2*ratio;c.beginPath();c.arc(x,y,5.5*ratio,0,Math.PI*2);c.fill();c.stroke();c.fillStyle='#ffe49b';c.beginPath();c.arc(x,top+mh+bottom*.72,3.5*ratio,0,Math.PI*2);c.arc(left+mw+right*.7,y,3.5*ratio,0,Math.PI*2);c.fill()}
  }
  window.ProjectionPanels={update:draw};
})();
