(function(){
  const states=new WeakMap(),allStates=new Set();let defaultDensity=3.6;
  const camera=`uniform float uYaw,uPitch,uZoom,uAspect;vec4 project3d(vec3 a){float cy=cos(uYaw),sy=sin(uYaw),cx=cos(uPitch),sx=sin(uPitch);vec3 p=vec3(cy*a.x+sy*a.z,a.y,-sy*a.x+cy*a.z);p=vec3(p.x,cx*p.y-sx*p.z,sx*p.y+cx*p.z);float depth=12.0-p.z;float ndcZ=((depth-.2)/(30.0-.2))*2.0-1.0;return vec4(p.x*uZoom*2.25/uAspect,p.y*uZoom*2.25,ndcZ*depth,depth);}`;
  const pointVertex=`attribute vec3 aPosition;attribute vec4 aColor;attribute float aSize;${camera} varying vec4 vColor;void main(){gl_Position=project3d(aPosition);gl_PointSize=aSize*(12.0/gl_Position.w);vColor=aColor;}`;
  const pointFragment=`precision mediump float;varying vec4 vColor;void main(){vec2 q=gl_PointCoord-.5;float r=length(q)*2.0;if(r>1.0)discard;float a=exp(-4.0*r*r);gl_FragColor=vec4(vColor.rgb*(.7+.5*exp(-14.0*r*r)),vColor.a*a);}`;
  const flatVertex=`attribute vec3 aPosition;attribute vec4 aColor;${camera} varying vec4 vColor;void main(){gl_Position=project3d(aPosition);vColor=aColor;}`;
  const flatFragment=`precision mediump float;varying vec4 vColor;void main(){gl_FragColor=vColor;}`;
  const slabVertex=`attribute vec3 aPosition;${camera} varying vec3 vPos;void main(){vPos=aPosition;gl_Position=project3d(aPosition);}`;
  const slabFragment=`precision mediump float;uniform vec4 uBranch[8];uniform vec4 uBranchColor[8];uniform vec4 uShape;uniform float uDensity;varying vec3 vPos;void main(){float dx=(vPos.x-uShape.x)/uShape.y;float gx=exp(-.5*dx*dx),dens=0.0;vec3 col=vec3(0.0);for(int i=0;i<8;i++){vec4 b=uBranch[i];float dy=(vPos.y-b.x)/uShape.z,dz=(vPos.z-b.y)/uShape.w;float d=gx*exp(-.5*(dy*dy+dz*dz))*b.z*b.w;dens+=d;col+=uBranchColor[i].rgb*d;}float cutoff=.018/max(uDensity,.35);if(dens<cutoff)discard;col/=max(dens,.0001);float edge=smoothstep(cutoff,cutoff*7.0,dens);float alpha=clamp(sqrt(dens)*.11*uDensity*edge,0.0,.34);gl_FragColor=vec4(col*(.72+.48*sqrt(dens)),alpha);}`;
  function shader(gl,type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s}
  function makeProgram(gl,vs,fs){const p=gl.createProgram();gl.attachShader(p,shader(gl,gl.VERTEX_SHADER,vs));gl.attachShader(p,shader(gl,gl.FRAGMENT_SHADER,fs));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p));return p}
  function resize(state){if(!state.canvas)return;const d=Math.min(devicePixelRatio||1,2),w=Math.max(2,state.host.clientWidth),h=Math.max(2,state.host.clientHeight);state.canvas.width=Math.round(w*d);state.canvas.height=Math.round(h*d);state.canvas.style.width=w+'px';state.canvas.style.height=h+'px';state.labelCanvas.width=Math.round(w*d);state.labelCanvas.height=Math.round(h*d);state.labelCanvas.style.width=w+'px';state.labelCanvas.style.height=h+'px';state.gl?.viewport(0,0,state.canvas.width,state.canvas.height);draw(state)}
  function common(state,p){const gl=state.gl;gl.uniform1f(gl.getUniformLocation(p,'uYaw'),state.yaw);gl.uniform1f(gl.getUniformLocation(p,'uPitch'),state.pitch);gl.uniform1f(gl.getUniformLocation(p,'uZoom'),state.zoom);gl.uniform1f(gl.getUniformLocation(p,'uAspect'),state.canvas.width/state.canvas.height)}
  function attr(state,p,name,size,data,key){const gl=state.gl,b=state.buffers[key]||(state.buffers[key]=gl.createBuffer());gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,data,gl.DYNAMIC_DRAW);const loc=gl.getAttribLocation(p,name);if(loc<0)return;gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,size,gl.FLOAT,false,0,0)}
  function flat(state,mode,positions,colors,key){if(!positions?.length)return;const gl=state.gl,p=state.flatProgram;gl.useProgram(p);common(state,p);attr(state,p,'aPosition',3,positions,key+'p');attr(state,p,'aColor',4,colors,key+'c');gl.drawArrays(mode,0,positions.length/3)}
  function fallback(state,d){const c=state.ctx,w=state.canvas.width,h=state.canvas.height,light=document.body.classList.contains('qontic-light');c.fillStyle=light?'#f7fbfd':'#03090f';c.fillRect(0,0,w,h);c.fillStyle=light?'#31566d':'#9fd5e8';c.font='14px Arial';c.fillText('This browser has disabled WebGL; use a WebGL-enabled browser for the perspective volume.',18,28)}
  function projectLabel(state,a){const cy=Math.cos(state.yaw),sy=Math.sin(state.yaw),cx=Math.cos(state.pitch),sx=Math.sin(state.pitch),x1=cy*a[0]+sy*a[2],y1=a[1],z1=-sy*a[0]+cy*a[2],x=x1,y=cx*y1-sx*z1,z=sx*y1+cx*z1,depth=12-z,w=state.host.clientWidth,h=state.host.clientHeight,aspect=w/h;return{x:(.5+.5*(x*state.zoom*2.25/aspect/depth))*w,y:(.5-.5*(y*state.zoom*2.25/depth))*h,visible:depth>0}}
  function drawLabels(state){const canvas=state.labelCanvas,d=state.data;if(!canvas||!d)return;const ratio=Math.min(devicePixelRatio||1,2),scale=d.labelScale||1.3,c=canvas.getContext('2d'),light=document.body.classList.contains('qontic-light');c.setTransform(ratio,0,0,ratio,0,0);c.clearRect(0,0,state.host.clientWidth,state.host.clientHeight);const label=(position,text,color,bold=false,row=0)=>{const p=projectLabel(state,position);if(!p.visible)return;const fontSize=(state.compact?9*Math.min(scale,1.2):12*scale),boxHeight=fontSize+7,y=p.y+row*(boxHeight+2);c.font=`${bold?'700':'600'} ${fontSize}px Arial`;const width=c.measureText(text).width;c.fillStyle=light?'rgba(248,252,254,.88)':'rgba(2,10,16,.82)';c.fillRect(p.x-4,y-boxHeight+3,width+8,boxHeight);c.fillStyle=color;c.fillText(text,p.x,y)};label([4.7,0,0],'X (system)',light?'#214c63':'#bfe8f4',true);label([0,3.6,0],'Y (pointer)',light?'#08717d':'#7cecf2',true);label([0,0,3.6],'Z (record)',light?'#9a6500':'#ffd37a',true);if(!state.compact&&d.detectorLabelPositions)for(let i=0;i<d.detectorLabels.length;i++)label(Array.from(d.detectorLabelPositions.slice(i*3,i*3+3)),d.detectorLabels[i],i===0?'#65e3ec':'#ffc35d',true,d.detectorLabelRows?.[i]||0)}
  function draw(state){const gl=state.gl,d=state.data,light=document.body.classList.contains('qontic-light');if(!d)return;if(!gl){fallback(state,d);return}light?gl.clearColor(.965,.982,.99,1):gl.clearColor(.012,.035,.058,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.BLEND);gl.disable(gl.DEPTH_TEST);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);flat(state,gl.TRIANGLES,d.planePositions,d.planeColors,'plane');
    gl.blendFunc(gl.SRC_ALPHA,light?gl.ONE_MINUS_SRC_ALPHA:gl.ONE);const sp=state.slabProgram;gl.useProgram(sp);common(state,sp);attr(state,sp,'aPosition',3,d.slabPositions,'slab');gl.uniform4fv(gl.getUniformLocation(sp,'uBranch[0]'),d.branchData);gl.uniform4fv(gl.getUniformLocation(sp,'uBranchColor[0]'),d.branchColors);gl.uniform4fv(gl.getUniformLocation(sp,'uShape'),d.slabShape);gl.uniform1f(gl.getUniformLocation(sp,'uDensity'),state.density);gl.drawArrays(gl.TRIANGLES,0,d.slabPositions.length/3);
    gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);flat(state,gl.LINES,d.axisPositions,d.axisColors,'axis');if(d.particlePositions?.length){gl.blendFunc(gl.SRC_ALPHA,light?gl.ONE_MINUS_SRC_ALPHA:gl.ONE);const pp=state.pointProgram;gl.useProgram(pp);common(state,pp);attr(state,pp,'aPosition',3,d.particlePositions,'particleP');attr(state,pp,'aColor',4,d.particleColors,'particleC');attr(state,pp,'aSize',1,d.particleSizes,'particleS');gl.drawArrays(gl.POINTS,0,d.particlePositions.length/3)}drawLabels(state)}
  function init(host,compact=false){let state=states.get(host);if(state&&(state.gl||state.ctx)&&state.canvas.parentNode===host){state.compact=compact;return state}state={host,canvas:null,labelCanvas:null,gl:null,ctx:null,pointProgram:null,flatProgram:null,slabProgram:null,buffers:{},yaw:-.72,pitch:.48,zoom:.82,density:defaultDensity,drag:null,data:null,compact};states.set(host,state);allStates.add(state);const canvas=document.createElement('canvas'),labelCanvas=document.createElement('canvas');canvas.setAttribute('aria-label','Perspective three-dimensional density rendered by translucent analytical slabs');canvas.style.cssText='display:block;width:100%;height:100%;cursor:grab;touch-action:none';labelCanvas.setAttribute('aria-hidden','true');labelCanvas.style.cssText='position:absolute;inset:0;pointer-events:none';host.replaceChildren(canvas,labelCanvas);state.canvas=canvas;state.labelCanvas=labelCanvas;const gl=canvas.getContext('webgl',{antialias:true,alpha:false,premultipliedAlpha:false});if(gl){state.gl=gl;state.pointProgram=makeProgram(gl,pointVertex,pointFragment);state.flatProgram=makeProgram(gl,flatVertex,flatFragment);state.slabProgram=makeProgram(gl,slabVertex,slabFragment)}else state.ctx=canvas.getContext('2d');canvas.addEventListener('pointerdown',e=>{state.drag={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);canvas.style.cursor='grabbing'});canvas.addEventListener('pointermove',e=>{if(!state.drag)return;state.yaw+=(e.clientX-state.drag.x)*.008;state.pitch=Math.max(-1.35,Math.min(1.35,state.pitch+(e.clientY-state.drag.y)*.008));state.drag={x:e.clientX,y:e.clientY};draw(state)});canvas.addEventListener('pointerup',e=>{state.drag=null;canvas.releasePointerCapture?.(e.pointerId);canvas.style.cursor='grab'});canvas.addEventListener('wheel',e=>{e.preventDefault();state.zoom=Math.max(.35,Math.min(1.65,state.zoom*(e.deltaY>0?.9:1.1)));draw(state)},{passive:false});new ResizeObserver(()=>resize(state)).observe(host);resize(state);return state}
  window.XYZWebGL={update(host,data,options={}){const state=init(host,!!options.compact);state.data=data;draw(state)},setDensity(value){defaultDensity=value;for(const state of allStates){state.density=value;draw(state)}},draw(){for(const state of allStates)draw(state)}};
})();
